<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ns_facebook_comment"
 *
 * Auto generated by Extension Builder 2018-05-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => '[NITSAN] Facebook Comment',
	'description' => 'This Extension help you to add and share comment as post with Facebook',
	'category' => 'plugin',
	'author' => 'Sanjay Chuahan [NITSAN Technologies]',
	'author_email' => 'sanjay@nitsan.in',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-9.5.9',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);