# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2018
  project: [NITSAN] Facebook Comments 
  version: 1.0
  release: 1.0.0
  latex_documents:
  - - Index
    - ns_facebook_comment.tex
    - [NITSAN] Facebook Comments 
    - Sanjay Chuahan [NITSAN Technologies]
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...
